export const SET_ADMIN = "SET_ADMIN";
export const SET_SING_IN_ERROR = "SET_SING_IN_ERROR";
export const SET_SING_UP_ERROR = "SET_SING_UP_ERROR";
export const SET_SCREEN = "SET_SCREEN";

export const SET_MEASUREMENT_DEVICES_NUM = "SET_MEASUREMENT_DEVICES_NUM";
export const SET_MEASUREMENT_ACTIVE_DEVICES_NUM = "SET_MEASUREMENT_ACTIVE_DEVICES_NUM";
export const SET_MEASUREMENT_DEVICES = "ADD_MEASUREMENT_DEVICES";

export const SET_CONSUMPTION_DEVICES_NUM = "SET_CONSUMPTION_DEVICES_NUM";
export const SET_CONSUMPTION_ACTIVE_DEVICES_NUM = "SET_CONSUMPTION_ACTIVE_DEVICES_NUM";
export const SET_CONSUMPTION_DEVICES = "ADD_CONSUMPTION_DEVICES";

export const SET_DEVICE_MODELS = "SET_DEVICE_MODELS";
export const SET_RESPONSE_OPTIONS = "SET_RESPONSE_OPTIONS";
export const SET_FARMS = "SET_FARMS";
export const SET_USERS = "SET_USERS";
